name: Build and Deploy Maven Package
on:
  push:
    branches:
      - automq_release
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '8'
          server-id: serverless-100005712758-hellocorp-rocketmq
          server-username: ${{ secrets.PRIVATE_MAVEN_USERNAME }}
          server-password: ${{ secrets.PRIVATE_MAVEN_PASSWORD }}
      - name: Build and Deploy
        run: |
          mvn clean package deploy -s ~/.m2/settings.xml